# Generated by Django 5.0.7 on 2024-12-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_debate_slug_remove_location_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="debate",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.RemoveIndex(
            model_name="debate",
            name="core_debate_created_fd42fa_idx",
        ),
        migrations.AddField(
            model_name="debate",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="debate",
            name="description_ru",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="debate",
            name="description_uz",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="debate",
            name="name_en",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="debate",
            name="name_ru",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="debate",
            name="name_uz",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="people",
            name="english_level",
            field=models.CharField(
                blank=True,
                choices=[("B1-B2", "B1-B2"), ("C1-C2", "C1-C2")],
                max_length=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="people",
            name="phone_number",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
