# Generated by Django 5.0.7 on 2025-01-28 13:05

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_ticket_debate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='qr_code_path',
            field=models.CharField(blank=True, default=core.models.create_qr_code, max_length=255, null=True),
        ),
    ]
