# Generated by Django 5.0.7 on 2025-01-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_ticket_qr_code_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='qr_code_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
